//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int uID { get; set; }
        public string uAd { get; set; }
        public Nullable<int> uMiktar { get; set; }
        public Nullable<int> uBrimFiyat { get; set; }
        public Nullable<System.DateTime> uSITarih { get; set; }
        public string uBarkod { get; set; }
    }
}
